import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Document, isMap, isSeq, parseDocument, type YAMLMap, type YAMLSeq } from "yaml";
import type { ResolvedConfig } from "../config/schema.js";
import { getGitHooksDir } from "../utils/git.js";

// Default values for hook configuration
const DEFAULT_CLI_NAME = "agconf";
const DEFAULT_CONFIG_DIR = ".agconf";
const DEFAULT_LOCKFILE_NAME = "lockfile.json";

// Hook identifier for detecting managed hooks (legacy and current)
const HOOK_IDENTIFIER = "# agconf pre-commit hook";

// Markers for identifying the agconf section within a hook
const HOOK_MARKER_START = "# agconf:hook:start";
const HOOK_MARKER_END = "# agconf:hook:end";

// Banner the pre-commit framework writes at the top of its generated
// `.git/hooks/pre-commit` launcher. Used to recognize a pre-commit setup even
// when `.pre-commit-config.yaml` is absent.
const PRE_COMMIT_BANNER = "File generated by pre-commit";

// The canonical pre-commit config filename (created when none exists).
const PRE_COMMIT_CONFIG_DEFAULT = ".pre-commit-config.yaml";
// Candidate names for the pre-commit framework config, in preference order.
// pre-commit reads `.pre-commit-config.yaml`; we also honor a `.yml` variant if
// that's what the repo already uses, and create the canonical `.yaml` otherwise.
const PRE_COMMIT_CONFIG_NAMES = [PRE_COMMIT_CONFIG_DEFAULT, ".pre-commit-config.yml"];

/**
 * Configuration for hook generation.
 */
export interface HookConfig {
  /** CLI command name (e.g., "agconf") */
  cliName: string;
  /** Config directory name (e.g., ".agconf") */
  configDir: string;
  /** Lockfile name (e.g., "lockfile.json") */
  lockfileName: string;
}

/**
 * Generate the marker-wrapped agconf hook section.
 * This is the single source of truth for the hook logic.
 * Can be used standalone (in a full hook) or appended to an existing hook.
 */
export function generateHookSection(config: HookConfig): string {
  const { cliName, configDir, lockfileName } = config;

  return `${HOOK_MARKER_START}
${HOOK_IDENTIFIER} - DO NOT EDIT THIS SECTION
_agconf_check() {
    local current_branch
    current_branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
    local repo_root
    repo_root=$(git rev-parse --show-toplevel)
    if [ ! -f "$repo_root/${configDir}/${lockfileName}" ]; then return 0; fi
    if ! command -v ${cliName} &> /dev/null; then return 0; fi
    local check_output check_exit
    cd "$repo_root"
    check_output=$(${cliName} check 2>&1) || check_exit=$?
    check_exit=\${check_exit:-0}
    if [ "$check_exit" -ne 0 ]; then
        case "$current_branch" in
            master|main)
                echo ""
                echo "Error: Cannot commit changes to ${cliName}-managed files"
                echo ""
                echo "Output from '${cliName} check' command:"
                echo "$check_output"
                echo ""
                echo "Options:"
                echo "  1. Discard your changes: git checkout -- <file>"
                echo "  2. Skip this check: git commit --no-verify"
                echo "  3. Restore managed files: ${cliName} sync"
                echo "  4. For AGENTS.md: edit only the repo-specific block (between repo:start and repo:end)"
                echo "  5. For skills: create a new custom skill instead"
                echo "  6. Propose changes upstream: ${cliName} propose"
                echo ""
                return 1
                ;;
            *)
                echo ""
                echo "Warning: committing changes to ${cliName}-managed files"
                echo ""
                echo "$check_output"
                echo ""
                echo "When ready, propose these changes upstream: ${cliName} propose"
                echo ""
                ;;
        esac
    fi
}
_agconf_check || exit 1
${HOOK_MARKER_END}`;
}

/**
 * Generate a full standalone pre-commit hook script.
 */
export function generatePreCommitHook(config: HookConfig): string {
  return `#!/bin/bash
${generateHookSection(config)}
exit 0
`;
}

/**
 * Get hook config from resolved config or use defaults.
 */
export function getHookConfig(config?: Partial<ResolvedConfig>): HookConfig {
  return {
    cliName: config?.cliName ?? DEFAULT_CLI_NAME,
    configDir: config?.configDir ?? DEFAULT_CONFIG_DIR,
    lockfileName: config?.lockfileName ?? DEFAULT_LOCKFILE_NAME,
  };
}

/** What happened to the `agconf-check` hook in `.pre-commit-config.yaml`. */
export type PreCommitAction = "created" | "registered" | "updated" | "unchanged";

export interface HookInstallResult {
  /**
   * Which integration path was taken. Absent or `"shell"` means the standalone
   * `.git/hooks/pre-commit` script; `"pre-commit"` means the repo uses the
   * pre-commit framework and agconf registered itself in `.pre-commit-config.yaml`.
   */
  mode?: "shell" | "pre-commit";
  installed: boolean;
  /** The file agconf wrote/managed (the hook script, or `.pre-commit-config.yaml`). */
  path: string;
  alreadyExisted: boolean;
  wasUpdated: boolean;
  wasAppended: boolean;
  /** Present only when `mode === "pre-commit"`. */
  preCommit?: {
    action: PreCommitAction;
    /**
     * True when the pre-commit framework's git hook isn't installed yet, so the
     * registered hook won't run until the user runs `pre-commit install`.
     */
    installNeeded: boolean;
  };
}

/**
 * Check if hook content contains agconf marker comments.
 */
function hasHookMarkers(content: string): boolean {
  return content.includes(HOOK_MARKER_START) && content.includes(HOOK_MARKER_END);
}

/**
 * Replace the agconf section (between and including markers) in existing hook content.
 */
function replaceHookSection(existingContent: string, newSection: string): string {
  const startIdx = existingContent.indexOf(HOOK_MARKER_START);
  const endIdx = existingContent.indexOf(HOOK_MARKER_END);
  if (startIdx === -1 || endIdx === -1) {
    return existingContent;
  }
  const before = existingContent.slice(0, startIdx);
  const after = existingContent.slice(endIdx + HOOK_MARKER_END.length);
  return before + newSection + after;
}

/** Outcome of probing a repo for a pre-commit framework setup. */
interface PreCommitDetection {
  /** The repo uses pre-commit (a config file exists, or the launcher is theirs). */
  usesPreCommit: boolean;
  /** Config file to manage — the existing one, or the default name to create. */
  configPath: string;
  /** Whether that config file already exists on disk. */
  configExists: boolean;
  /** Whether `.git/hooks/pre-commit` is the pre-commit framework's launcher. */
  launcherInstalled: boolean;
}

/**
 * Detect whether the repo at `repoRoot` uses the pre-commit framework.
 *
 * A repo counts as pre-commit-managed if it has a `.pre-commit-config.yaml`
 * (or `.yml`), or if its installed `<hooksDir>/pre-commit` carries pre-commit's
 * generated banner. Either way, appending agconf's shell section to the launcher
 * would be unreachable dead code, so we register a pre-commit hook instead.
 */
async function detectPreCommit(repoRoot: string, hooksDir: string): Promise<PreCommitDetection> {
  let configPath: string | null = null;
  for (const name of PRE_COMMIT_CONFIG_NAMES) {
    const candidate = path.join(repoRoot, name);
    try {
      await fs.access(candidate);
      configPath = candidate;
      break;
    } catch {
      // Expected: this candidate config name doesn't exist
    }
  }

  let launcherInstalled = false;
  try {
    const launcher = await fs.readFile(path.join(hooksDir, "pre-commit"), "utf-8");
    launcherInstalled = launcher.includes(PRE_COMMIT_BANNER);
  } catch {
    // Expected: no installed pre-commit hook
  }

  return {
    usesPreCommit: configPath !== null || launcherInstalled,
    configPath: configPath ?? path.join(repoRoot, PRE_COMMIT_CONFIG_DEFAULT),
    configExists: configPath !== null,
    launcherInstalled,
  };
}

/**
 * The canonical `agconf-check` pre-commit hook definition. Keyed off `cliName`
 * so a custom CLI name (e.g. `myagent`) produces `myagent-check`.
 */
function buildPreCommitHookFields(cliName: string): Record<string, string | boolean> {
  return {
    id: `${cliName}-check`,
    name: `${cliName} check`,
    entry: `${cliName} check --hook`,
    language: "system",
    pass_filenames: false,
    always_run: true,
    // Surface the feature-branch warning (a passing exit code) under pre-commit,
    // which otherwise only shows a hook's output when it fails.
    verbose: true,
  };
}

/** Find the `agconf-check` hook map within a parsed `repos:` sequence. */
function findManagedHook(repos: YAMLSeq, hookId: string): YAMLMap | null {
  for (const repo of repos.items) {
    if (!isMap(repo)) continue;
    const hooks = repo.get("hooks");
    if (!isSeq(hooks)) continue;
    for (const hook of hooks.items) {
      if (isMap(hook) && hook.get("id") === hookId) {
        return hook;
      }
    }
  }
  return null;
}

/**
 * Create or update the `agconf-check` hook in `.pre-commit-config.yaml`,
 * preserving the rest of the file (including comments) via the `yaml`
 * document API. Idempotency keys off the stable hook `id`, not text markers.
 */
async function registerPreCommitHook(
  configPath: string,
  hookConfig: HookConfig,
): Promise<PreCommitAction> {
  const fields = buildPreCommitHookFields(hookConfig.cliName);
  const hookId = fields.id as string;

  let existingContent: string | null = null;
  try {
    existingContent = await fs.readFile(configPath, "utf-8");
  } catch {
    // Expected: config file doesn't exist yet
  }
  const fileExisted = existingContent !== null;

  const doc =
    existingContent !== null && existingContent.trim() !== ""
      ? parseDocument(existingContent)
      : new Document();
  if (doc.errors.length > 0) {
    throw new Error(
      `Cannot parse ${path.basename(configPath)}: ${doc.errors[0]?.message ?? "invalid YAML"}`,
    );
  }

  // Ensure a `repos:` sequence exists to attach the hook to.
  if (!isSeq(doc.get("repos"))) {
    doc.set("repos", []);
  }
  const repos = doc.get("repos") as YAMLSeq;

  const existing = findManagedHook(repos, hookId);
  let didAdd = false;
  let didUpdate = false;

  if (existing) {
    // Reconcile every managed field; only write if something actually changed.
    for (const [key, value] of Object.entries(fields)) {
      if (existing.get(key) !== value) {
        existing.set(key, value);
        didUpdate = true;
      }
    }
  } else {
    repos.add(doc.createNode({ repo: "local", hooks: [fields] }));
    didAdd = true;
  }

  if (didAdd || didUpdate) {
    await fs.writeFile(configPath, doc.toString(), "utf-8");
  }

  if (didAdd) return fileExisted ? "registered" : "created";
  if (didUpdate) return "updated";
  return "unchanged";
}

/**
 * Install agconf's pre-commit integration in a git repository.
 *
 * If the repo uses the pre-commit framework, agconf registers an `agconf-check`
 * hook in `.pre-commit-config.yaml` and leaves the generated launcher alone
 * (appending to it would be dead code). Otherwise it manages a standalone
 * `.git/hooks/pre-commit` script: writing a fresh one, or appending/updating the
 * agconf section (delimited by marker comments) in an existing custom hook.
 */
export async function installPreCommitHook(
  targetDir: string,
  config?: Partial<ResolvedConfig>,
): Promise<HookInstallResult> {
  const hookConfig = getHookConfig(config);
  // Resolve the real hooks dir so this works inside a linked worktree (where
  // `.git` is a file, not a directory) and with a custom core.hooksPath.
  // Fall back to the conventional location if resolution fails.
  const hooksDir = (await getGitHooksDir(targetDir)) ?? path.join(targetDir, ".git", "hooks");
  const hookPath = path.join(hooksDir, "pre-commit");

  // Pre-commit framework integration: register a managed hook in
  // `.pre-commit-config.yaml` instead of appending unreachable code to the
  // pre-commit launcher.
  const preCommit = await detectPreCommit(targetDir, hooksDir);
  if (preCommit.usesPreCommit) {
    const action = await registerPreCommitHook(preCommit.configPath, hookConfig);
    return {
      mode: "pre-commit",
      installed: true,
      path: preCommit.configPath,
      alreadyExisted: preCommit.configExists,
      wasUpdated: action === "updated",
      wasAppended: action === "registered" || action === "created",
      preCommit: { action, installNeeded: !preCommit.launcherInstalled },
    };
  }

  const hookSection = generateHookSection(hookConfig);
  const fullHook = generatePreCommitHook(hookConfig);

  // Ensure hooks directory exists
  await fs.mkdir(hooksDir, { recursive: true });

  // Check if hook already exists
  let existingContent: string | null = null;
  try {
    existingContent = await fs.readFile(hookPath, "utf-8");
  } catch {
    // Expected: hook file doesn't exist yet
  }

  // Case 1: No existing hook — write full standalone hook
  if (existingContent === null) {
    await fs.writeFile(hookPath, fullHook, { mode: 0o755 });
    return {
      installed: true,
      path: hookPath,
      alreadyExisted: false,
      wasUpdated: false,
      wasAppended: false,
    };
  }

  // Case 2: Existing hook with markers — update or no-op
  if (hasHookMarkers(existingContent)) {
    const updated = replaceHookSection(existingContent, hookSection);
    if (updated === existingContent) {
      // Section is already current
      return {
        installed: true,
        path: hookPath,
        alreadyExisted: true,
        wasUpdated: false,
        wasAppended: true,
      };
    }
    // Section was outdated, replace it
    await fs.writeFile(hookPath, updated, { mode: 0o755 });
    return {
      installed: true,
      path: hookPath,
      alreadyExisted: true,
      wasUpdated: true,
      wasAppended: true,
    };
  }

  // Case 3: Legacy agconf hook (has identifier but no markers) — replace entirely
  if (existingContent.includes(HOOK_IDENTIFIER)) {
    await fs.writeFile(hookPath, fullHook, { mode: 0o755 });
    return {
      installed: true,
      path: hookPath,
      alreadyExisted: true,
      wasUpdated: true,
      wasAppended: false,
    };
  }

  // Case 4: Custom hook with no agconf content — append section
  const separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
  const appended = `${existingContent}${separator}${hookSection}\n`;
  await fs.writeFile(hookPath, appended, { mode: 0o755 });
  return {
    installed: true,
    path: hookPath,
    alreadyExisted: true,
    wasUpdated: false,
    wasAppended: true,
  };
}
